apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-04T17:09:21Z"
  generation: 1
  labels:
    run: nginxk8s
  name: nginxk8s
  namespace: default
  resourceVersion: "20954"
  uid: ea59f54b-e4fc-4189-863c-9fa948598b43
spec:
  containers:
  - image: nginx:1.27
    imagePullPolicy: IfNotPresent
    name: nginxk8s
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-f6hcj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-f6hcj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T17:10:25Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T17:09:21Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T17:10:25Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T17:10:25Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-12-04T17:09:21Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0f68d64b87be7e47ee829472158bb952cfcd4089fcb2bc942573b4f3f10fd191
    image: nginx:1.27
    imageID: docker-pullable://nginx@sha256:6784fb0834aa7dbbe12e3d7471e69c290df3e6ba810dc38b34ae33d3c1c05f7d
    lastState: {}
    name: nginxk8s
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-12-04T17:10:25Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-f6hcj
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.65.3
  hostIPs:
  - ip: 192.168.65.3
  observedGeneration: 1
  phase: Running
  podIP: 10.1.0.6
  podIPs:
  - ip: 10.1.0.6
  qosClass: BestEffort
  startTime: "2025-12-04T17:09:21Z"
