name: Docker CI
run-name: Docker4o 

on:
   pull_request:
      branches:
        - main
jobs:
   ci:
      runs-on: ubuntu-latest
      steps:
        - name: Lint Checkout code
          uses: actions/checkout@v4

        - name: Lint Build Docker image
          run: docker build -t redzek/pythonenv:latest .

        - name: Lint Run container test
          run: docker run --rm redzek/pythonenv:latest echo "âœ… Container works fine!"
          

        
          